language: python
  
python: "3.6"
  
# don't clone more than necessary
git:
  depth: 1
  
# Install dependencies
install:
  # - pip install -r requirements.txt
  - pip install codecov

  
# script to run tests. Script can have many commands, one per line.
script: 
  - python -m unittest discover -p "*_test.py"
  - coverage run fraction_test.py

after_success:
  - export CODECOV_TOKEN="6f671d19-122b-41ac-a1c3-8e1c81b22083"
  - codecov